### ISSUE TITLE
data is returned as NULL when use_unicode=0

### ISSUE THREAD

**Issue by zzzeek** [nakagami/CyMySQL#15]
Using cymysql 0.8.6, Python 2.7.11 on Fedora 23, and MariaDB 10.0.23, if use_unicode is not set to True, basic textual results return None:

    import cymysql

    print cymysql.__version__

    conn1 = cymysql.connect(use_unicode=1)
    conn2 = cymysql.connect()

    def test(conn):
        cursor = conn.cursor()

        cursor.execute("SELECT 'any old text'")
        print cursor.fetchall()

        cursor.execute("SELECT @@tx_isolation")

        print cursor.fetchall()

    test(conn1)
    test(conn2)

output:

    $ python test3.py 
    0.8.6
    [(u'any old text',)]
    [(u'REPEATABLE-READ',)]
    [(None,)]
    [(None,)]

this seems pretty serious can you please confirm?    I can close my downstream issue then.

**Comment by nakagami** [comment]
Thanks, I is fixed I think, and 0.8.7 released.
Is this issue fixed ?

**Comment by zzzeek** [comment]
yup we are back now thanks!
