### ISSUE TITLE
Missing charset 46 (utf8mb4_bin)

### ISSUE THREAD

**Issue by Diggsey** [nakagami/CyMySQL#16]
`pymysql` has an entry for this charset but it's missing from `cymysql`

**Comment by nakagami** [comment]
Sorry I have mistake about commit log. but fix this issue.
https://github.com/nakagami/CyMySQL/commit/154bf397cda8d0a3e69781cd9d7d994c133395c4
Thanks

**Comment by Diggsey** [comment]
Cool, thanks for the quick fix.
