### ISSUE TITLE
Error Build with Cython

### ISSUE THREAD

**Issue by suryakencana007** [nakagami/CyMySQL#24]
Cannot build cymsql with cython

`running build_ext
  building 'cymysql.packet' extension
  creating build/temp.macosx-10.13-x86_64-3.6
  creating build/temp.macosx-10.13-x86_64-3.6/cymysql
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c cymysql/packet.c -o build/temp.macosx-10.13-x86_64-3.6/cymysql/packet.o
  cymysql/packet.c:806:7: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    int errno;
        ^
  /usr/include/sys/errno.h:81:24: note: expanded from macro 'errno'
  #define errno (*__error())`

**Comment by nakagami** [comment]
Now, I modify a bit ffb4158 .

Does this latest master revision show same error message?

**Comment by nakagami** [comment]
Probably fix it.
Can you test with master HEAD ?

**Comment by suryakencana007** [comment]
hi Nakagami,

thank for fast response,
now that issue solved, after i had installed mysql-connector-c
suddenly cymysql can be installed :-)

**Comment by nakagami** [comment]
thanks
