### ISSUE TITLE
Limited support: authentication plugins

### ISSUE THREAD

**Issue by Code-ReaQtor** [nakagami/CyMySQL#26]
Hi,

I encountered the following error lately:
`NotImplementedError: mysql_clear_password authentication plugin is not implemented`

Found out that **CyMySQL** only support `mysql_native_password` and `caching_sha2_password`.

**PyMySQL** , on the the hand, support other plugins like `sha256_password`, `mysql_old_password`, `mysql_clear_password`, etc.  See (https://github.com/PyMySQL/PyMySQL/blob/f0bbe54ef7f977c8cc8a55f583e85d06bea44e7c/pymysql/connections.py#L881)

It would be better if **CyMySQL** support can be extended since this library is fast compared to **PyMySQL**.

Cheers!

**Comment by nakagami** [comment]
I heard that  Amazon RDS IAM authentication use  mysql_clear_password.
So I hope support mysql_clear_password at least.

I add it now.
Can you connect with mysql_clear_password plugin ?
Sorry I don't know how to set up my local environment.

**Comment by Code-ReaQtor** [comment]
Hi @nakagami ,

I build the master branch on Windows and Python 3.6/3,7 and I am getting the following error:

```
  File "cymysql\connections.py", line 248, in cymysql.connections.Connection.__init__
  File "cymysql\connections.py", line 416, in cymysql.connections.Connection._connect
  File "cymysql\connections.py", line 507, in cymysql.connections.Connection._request_authentication
AttributeError: 'cymysql.packet.MysqlPacket' object has no attribute 'read_auth_switch_request'
```

**Comment by nakagami** [comment]
Oh, sorry. It is not result for this commit.
Wait

**Comment by Code-ReaQtor** [comment]
Cython-0.28.3

Probably a compiler issue. I'm using Microsoft Visual C++ 14.0
It will probably work with MinGW but cannot test that now.

**Comment by nakagami** [comment]
Now, release version 0.9.12 in pypi.

**Comment by Code-ReaQtor** [comment]
Thanks @nakagami 

Are there plans to add other plugins?

**Comment by nakagami** [comment]
Not yet.

**Comment by Code-ReaQtor** [comment]
Let's close this ticket for now.

Thanks @nakagami 🥂
