### ISSUE TITLE
CyMySQL cannot detect encoding of database

### ISSUE THREAD

**Issue by roniemartinez** [nakagami/CyMySQL#29]
I recently encountered failure to insert unicode characters to a table even though the database and tables are already in unicode.

Here are the current conditions:
1. Same tests works on PyMySQL but not on CyMySQL.
2. Tests on CyMySQL only works when **explicitly** specifying `charset='utf8mb4'`

EDIT: This is in Python 3 which should automatically use unicode.

**Comment by nakagami** [comment]
Please show me that Traceback or any error messages.

**Comment by roniemartinez** [comment]
Here is the error code, unfortunately, I cannot show everything:
![image](https://user-images.githubusercontent.com/2573537/61504191-14192600-aa0d-11e9-8f7e-1bef7ee8e055.png)

That is just a normal error code when inserting an emoji into a database. However, the database and the tables are already set up in **utf8mb4** (charset) and **utf8mb4_unicode_ci** (collation).

This is the CyMySQL code that does not work:
```python
connection = cymysql.connect(host=host, port=port, user=user, passwd=password, db=db)
```

However, it's equivalent PyMySQL code works by just changing the module
```python
connection = pymysql.connect(host=host, port=port, user=user, passwd=password, db=db)
```

By explicitly specifying charset, CyMySQL works.
```python
connection = cymysql.connect(host=host, port=port, user=user, passwd=password, db=db, charset='utf8mb4')
```

This is not the intended behavior of CyMySQL (based on source) for Python 3 as it should default to using unicode.

**Comment by nakagami** [comment]
Thanks, I understand.

Can you test with master HEAD branch on Github ?

**Comment by roniemartinez** [comment]
INSERT query works, however, it fails when SELECT is used to cross-check

```
E       AssertionError: assert '\U0001f40d' == '\xf0\\x9f\\x90\\x8d'
E         - \U0001f40d
E         ? ^
E         + \xf0\x9f\x90\x8d
E         ? ^^^^
```

Here are the original and SELECTed data
```
🐍
ð
```

Explicitly specifying **charset='utf8mb4'** will output the correct emoji. I believe, the decoding side was not set.

**Comment by nakagami** [comment]
thanks

**Comment by nakagami** [comment]
version 0.9.14 released
Please check it

**Comment by roniemartinez** [comment]
@nakagami Verified! Thank you!
