### ISSUE TITLE
No cythonized extensions even with Cython installed

### ISSUE THREAD

**Issue by phdru** [nakagami/CyMySQL#39]
[The README says](https://github.com/nakagami/CyMySQL/blob/ac71e025850f8a4b76c6beb5a5e28d4079beae6b/README.rst?plain=1#L35) CyMySQL will run faster if Cython is installed but that's not exactly true with the modern `pip`. The latest versions of `pip` build sources into a wheel in a separate ("isolated") virtual environment where Cython is not installed. You can easily check it yourself: create a new venv, activate it and run
```sh
pip install cython
pip install cymysql
```
Lookup into `site-packages/cymysql/` — there are no dynamic (shared) libraries.

The correct fix is to create `pyproject.toml` and list Cython as a build dependency. OTOH there will no longer be a way to install CyMySQL without Cython.

A workaround is to build without separate venv but that must be explicit and should be documented for users. These are the commands:
```sh
pip install cython setuptools
pip install --no-build-isolation cymysql
```

**Comment by nakagami** [comment]
Thank you for your report.
I did not notice that.

I have no experience writing pyproject.toml yet.
Is there anyone who can help me?

I'm currently trying to get it to work with Python 2.7, but I'm not sure if that's possible anymore.

**Comment by nakagami** [comment]
Looking bellow, do I just add pyproject.toml?

https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

**Comment by phdru** [comment]
> Thank you for your report. I did not notice that.

No problem, that's why we are here! :-)

> I have no experience writing pyproject.toml yet. Is there anyone who can help me?

Sure. I'll debug it and send a pull request. Hope to do that in a few days.

> I'm currently trying to get it to work with Python 2.7, but I'm not sure if that's possible anymore.

I just tested with Python 2.7, 3.7, 3.11, 3.12 and 3.13rc2. The problem appeared only with 3.12 and 3.13, older Pythons are ok, `pip install cython` is enough for them.

**Comment by nakagami** [comment]
If you could fix the README too I'd be happy.

**Comment by phdru** [comment]
I debugged it and ready to send a pull request.

Last question: why minimal version is 3.8? `async`/`await` require Python 3.7, but the rest of the code? I hoped it's compatible with at least 3.6. I'll try to test…

> If you could fix the README too I'd be happy.

A little bit, sure.

**Comment by nakagami** [comment]
I have only tested 3.8 and above because 3.7 was dropped by Github actions.
https://github.com/nakagami/CyMySQL/blob/master/.github/workflows/test.yml#L26

Python3 should work with 3.8 or higher

**Comment by phdru** [comment]
I'm gonna to add CyMySQL to [SQLObject](https://github.com/sqlobject/sqlobject) which supports Python 2.7 and 3.4+. I'll test CyMySQL with wider range of Python versions, both pure Python and cythonized.

I install Pythons [from conda](https://github.com/sqlobject/sqlobject/blob/bfcc0f135bb0008692bf57ad3e31e8aeb08b8c8a/.github/workflows/run-tests.yaml#L46-L51).

**Comment by phdru** [comment]
I tested — CyMySQL works with Python 2.7 and 3.5+. Without importing `aio` it perhaps would work with 3.4.

**Comment by nakagami** [comment]
Thanks
